### ISSUE TITLE
默认还是会走curl handler

### ISSUE THREAD

**Issue by osakey** [mix-php/guzzle#1]
https://github.com/mix-php/guzzle-hook/blob/6989c92fe83d700ea531031ca26a1157d7625216/src/functions_include.php#L8 
这个变量会覆盖Guzzle的，导致版本获取错误。
另外，经测试， 还是走的curl handler

**Comment by onanying** [comment]
已经修复，已经测试通过，清除 composer 缓存，重新安装 v1.0.1
